In [49]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

X_train = [['Python'], ['Java'], ['Java'], ['C++']]

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

X_train_encoded = encoder.fit_transform(X_train)
columns = encoder.categories_[0]
print(columns)

df_train = pd.DataFrame(X_train_encoded, columns=columns)
df_train

['C++' 'Java' 'Python']

   C++  Java  Python
0  0.0   0.0     1.0
1  0.0   1.0     0.0
2  0.0   1.0     0.0
3  1.0   0.0     0.0

In [50]:
X_test = [['Python'], ['Java'], ['C'], ['C++']]

X_test_encoded = encoder.transform(X_test)
df_test = pd.DataFrame(X_test_encoded, columns=columns)
df_test

   C++  Java  Python
0  0.0   0.0     1.0
1  0.0   1.0     0.0
2  0.0   0.0     0.0
3  1.0   0.0     0.0